baseurl = "https://saswatac.github.io" # Hostname (and path) to the root.
title = "Saswata Chakravarty" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Saswata Chakravarty" # Author's name.
    info = "Software Engineer" # Author's job title or info.
    description = "Saswata Chakravarty's personal website" # Site description.
    keywords = "blog,developer,personal,ai,machine learning" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # snsShare = true

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/saswatac"
    icon = "fab fa-github"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/iamsaswata"
    icon = "fab fa-twitter"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/saswatac/"
    icon = "fab fa-linkedin-in"
[[params.social]]
    name = "Medium"
    weight = 4
    url = "https://saswatac.medium.com"
    icon = "fab fa-medium-m"
[[params.social]]
    name = "Instagram"
    weight = 4
    url = "https://www.instagram.com/saswatachak/"
    icon = "fab fa-instagram"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
