baseurl = "https://saswatac.github.io"
title = "Saswata Chakravarty"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Saswata Chakravarty"
    description = "Saswata Chakravarty's personal website"
    keywords = "blog,developer,personal,ai,data,deep learning"
    info = "Software and Machine Learning Engineer"
    avatarurl = "images/avatar.jpg"
    #footercontent = "Enter a text here."
    #fixedbarContent = "Do you want to know me more private?→"
    #fixedbarContentAfter = "Thank You! Please share it if you like it→"

    hideCredits = false
    hideCopyright = false

    # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false
    enableFacebookShare = false
    enableHatenaShare = false
    enableLineShare = false
    enableLinkedInShare = false

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    icon = "fab fa-2x fa-github"
    weight = 1
    url = "https://github.com/saswatac/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-2x fa-twitter"
    weight = 2
    url = "https://twitter.com/iamsaswata/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-2x fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/saswatac/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-2x fa-medium"
    weight = 4
    url = "https://saswatac.medium.com"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.


        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "about"
